export const CHANGE_PREVIEW_MONTH = 'CHANGE_PREVIEW_MONTH';
export const TOGGLE_FISH_CAUGHT = 'TOGGLE_FISH_CAUGHT';
export const TOGGLE_HIDE_CAUGHT = 'TOGGLE_HIDE_CAUGHT';
export const CHANGE_MONTH_FILTER = 'CHANGE_MONTH_FILTER';
