export const CHANGE_PREVIEW_MONTH = 'CHANGE_PREVIEW_MONTH';
export const TOGGLE_CRITTER_CAUGHT = 'TOGGLE_CRITTER_CAUGHT';
export const TOGGLE_HIDE_CAUGHT = 'TOGGLE_HIDE_CAUGHT';
export const CHANGE_MONTH_FILTER = 'CHANGE_MONTH_FILTER';
export const CHANGE_TYPE_FILTER = 'CHANGE_TYPE_FILTER';
export const CHANGE_HEMISPHERE = 'CHANGE_HEMISPHERE';
